#!/usr/bin/env python3
"""Rebuild the FLAG_DOCS table inside index.html from AOSP.

Oriel ships as one file with no build step, so the flag text lives inline. This
script is how that block is written: it reads WindowManager.java straight from
android.googlesource.com, pulls the javadoc of every FLAG_*, PRIVATE_FLAG_* and
SYSTEM_FLAG_* constant, keys it by the name the ViewDebug tables make dumpsys
print, and splices the result between the markers in index.html.

    python3 tools/flag-docs.py            # rewrite index.html in place
    python3 tools/flag-docs.py --check    # exit 1 if the file is out of date
    python3 tools/flag-docs.py --print    # write the block to stdout instead

Several branches are read, newest first, and the first release to define a name
wins. That is deliberate: a dump from an old build can carry a flag that main
has since deleted, and Oriel should still have text for it.
"""

import argparse
import base64
import json
import pathlib
import re
import sys
import urllib.request

HERE = pathlib.Path(__file__).resolve().parent
INDEX = HERE.parent / "index.html"

SOURCE = ("https://android.googlesource.com/platform/frameworks/base/+/"
          "refs/heads/{branch}/core/java/android/view/WindowManager.java?format=TEXT")

# Newest first. Earlier branches win, so main's wording is what you normally see.
BRANCHES = ["main", "android14-release", "android13-release",
            "android12-release", "android11-release", "android10-release"]

BEGIN = "/* >>> flag docs, generated by tools/flag-docs.py — do not edit by hand"
END = "/* <<< end flag docs */"

CONST = r"(?:FLAG|PRIVATE_FLAG|SYSTEM_FLAG)_[A-Z0-9_]+"

# A doc comment, any annotations, then the constant and its value.
DECL_RE = re.compile(
    r"/\*\*((?:(?!\*/).)*?)\*/\s*"
    r"((?:@[\w.]+(?:\((?:[^()]|\([^()]*\))*\))?\s*)*)"
    r"public static final int (" + CONST + r")\s*=\s*([^;]+);", re.S)

# The tables that decide what dumpsys actually prints for a set bit.
NAME_RE = re.compile(
    r"@ViewDebug\.FlagToString\(\s*mask\s*=\s*" + CONST +
    r"\s*,\s*equals\s*=\s*(" + CONST + r')\s*,\s*name\s*=\s*"([A-Z0-9_]+)"', re.S)

# Two flags share one printed name in the ViewDebug table, so no dump can say
# which of them is set. Neither javadoc alone would be honest here.
OVERRIDES = {
    "LOCAL_FOCUS_MODE": {
        "c": "FLAG_LOCAL_FOCUS_MODE or FLAG_LAYOUT_IN_OVERSCAN",
        "v": "0x10000000 / 0x02000000",
        "d": ("Ambiguous: WindowManager prints this one name for two flags, and the dump does "
              "not say which is set. FLAG_LOCAL_FOCUS_MODE (0x10000000) marks a window in local "
              "focus mode, which controls focus itself through Window.setLocalFocus instead of "
              "through the window manager. FLAG_LAYOUT_IN_OVERSCAN (0x02000000) let window "
              "contents extend into the display's overscan area, and is deprecated — no "
              "Android product has set an overscan area since Android 11."),
    },
}


def fetch(branch):
    with urllib.request.urlopen(SOURCE.format(branch=branch), timeout=60) as r:
        return base64.b64decode(r.read()).decode("utf-8")


def untag(text):
    """Javadoc markup out, plain sentences in."""
    lines = [re.sub(r"^\*\s?", "", ln.strip()) for ln in text.split("\n")]
    t = "\n".join(lines)

    def link(m):
        cls, member, label = m.group(1), m.group(2), m.group(3).strip()
        if label:
            return label
        cls = cls.split(".")[-1]
        return f"{cls}.{member}" if cls else member

    t = re.sub(r"\{@link\s+([\w.]*)#(\w+)(?:\([^)]*\))?\s*([^}]*)\}", link, t)
    t = re.sub(r"\{@link\s+([^}\s]+)\s*([^}]*)\}",
               lambda m: m.group(2).strip() or m.group(1).split(".")[-1], t)
    t = re.sub(r"\{@code\s+([^}]*)\}", r"\1", t)
    t = re.sub(r"\{@hide\}?", "", t)
    t = re.sub(r"<li>", " • ", t, flags=re.I)
    t = re.sub(r"<[^>]+>", "", t)
    for ent, ch in (("&lt;", "<"), ("&gt;", ">"), ("&amp;", "&"), ("&nbsp;", " ")):
        t = t.replace(ent, ch)
    return re.sub(r"\s{2,}", " ", t.replace("\n", " ")).strip()


def summarize(s, soft=280, hard=420):
    """A tooltip is not a manual: keep whole sentences up to about a paragraph."""
    if len(s) <= hard:
        return s
    out = ""
    for sentence in re.findall(r"[^.!?]*[.!?]+|\S+$", s):
        if out and len(out) + len(sentence) > hard:
            break
        out += sentence
        if len(out) >= soft:
            break
    out = (out or s[:hard]).strip()
    return out + " …" if len(out) < len(s) else out


def value(expr):
    expr = expr.strip()
    m = re.fullmatch(r"0x([0-9a-fA-F]+)", expr)
    if m:
        return int(m.group(1), 16)
    m = re.fullmatch(r"1\s*<<\s*(\d+)", expr)
    return 1 << int(m.group(1)) if m else None


def harvest():
    consts, names = {}, {}
    for branch in BRANCHES:
        src = fetch(branch)
        for m in DECL_RE.finditer(src):
            const = m.group(3)
            if const in consts:
                continue
            doc = untag(m.group(1))
            body = re.split(r"\s@(?:deprecated|hide|see|param|attr|removed)\b", doc)[0]
            dep = re.search(r"@deprecated\s+(.*?)(?=\s@\w+\s|\Z)", doc)
            consts[const] = {
                "doc": summarize(body.strip()),
                "dep": dep.group(1).strip() if dep else None,
                "val": value(m.group(4)),
                "hide": "@hide" in m.group(1),
                "sys": "@SystemApi" in m.group(2),
            }
        for m in NAME_RE.finditer(src):
            names.setdefault(m.group(2), m.group(1))

    table = {}
    for name, const in names.items():
        c = consts[const]
        entry = {"c": const, "d": c["doc"]}
        if c["val"] is not None:
            entry["v"] = "0x%08x" % c["val"]
        if c["dep"]:
            entry["x"] = c["dep"]
        if c["sys"]:
            entry["h"] = 2
        elif c["hide"]:
            entry["h"] = 1
        table[name] = entry
    table.update(OVERRIDES)
    return table


def render(table):
    rows = "\n".join(
        " %s: %s," % (json.dumps(k), json.dumps(table[k], ensure_ascii=False, sort_keys=True))
        for k in sorted(table))
    return (
        f"{BEGIN}\n"
        "   Official text for the flag names dumpsys prints, lifted from the javadoc of\n"
        "   WindowManager.LayoutParams in AOSP (FLAG_*, PRIVATE_FLAG_* and SYSTEM_FLAG_*).\n"
        "   c = constant, v = value, d = doc, x = @deprecated note, h = 1 @hide / 2 @SystemApi.\n"
        "   Names are the ones in the ViewDebug flag tables, so they cover several releases:\n"
        "   a dump from an old build can carry a flag that no longer exists on main. */\n"
        "const FLAG_DOCS = {\n" + rows + "\n};\n" + END)


def splice(page, block):
    start, end = page.index(BEGIN), page.index(END) + len(END)
    return page[:start] + block + page[end:]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if index.html does not already hold this block")
    ap.add_argument("--print", dest="to_stdout", action="store_true",
                    help="write the block to stdout and leave index.html alone")
    args = ap.parse_args()

    block = render(harvest())
    if args.to_stdout:
        print(block)
        return 0

    page = INDEX.read_text()
    updated = splice(page, block)
    if args.check:
        if updated == page:
            print("flag table is up to date")
            return 0
        print("flag table is out of date; run tools/flag-docs.py", file=sys.stderr)
        return 1
    if updated == page:
        print("flag table unchanged")
        return 0
    INDEX.write_text(updated)
    print("flag table rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main())
